name: Android CI

on:
 push:
  branches:
   - ci

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build
    - name: Build Debug APK
      run: ./gradlew assembleDebug
    - name: Upload debug Apk to Telegram
      run: |
       cd $(pwd)/app/build/outputs/apk/debug/
       debugAPK=$(echo *.apk)
       echo "Debug APK = "$debugAPK
       curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendDocument -F chat_id=${{ secrets.TELEGRAM_TO }} -F document="@$debugAPK" -F caption="Android TorchLigh App."
       cd ../../../../../
    - name: Generate Signed APK
      uses: r0adkll/sign-android-release@v1
      with:
         releaseDirectory: app/build/outputs/apk/release
         signingKeyBase64: ${{ secrets.SIGNING_KEY }}
         alias: ${{ secrets.ALIAS }}
         keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
         keyPassword: ${{ secrets.KEY_PASSWORD }} 
    - name: Debug APK Publisher
      uses: ShaunLWM/action-release-debugapk@0.0.5
      env:
       GITHUB_TOKEN: ${{ secrets.TOKEN }}
       APP_FOLDER: app
       RELEASE_TITLE: TorchLight
