name: Android CI

on:
 push:
  branches:
   - ci

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build
    - name: Build Debug APK
      run: ./gradlew assembleDebug
#     - name: Debug APK Publisher
#       uses: ShaunLWM/action-release-debugapk@0.0.5
#       env:
#        GITHUB_TOKEN: ${{ secrets.TOKEN }}
#        APP_FOLDER: app
#        RELEASE_TITLE: TorchLight
    - name: Telegram Notify
      uses: appleboy/telegram-action@0.0.3
      with:
       to: ${{ secrets.TELEGRAM_TO }}
       token: ${{ secrets.TELEGRAM_TOKEN }}
       message: Android TorchLight 
#        document: app/build/outputs/apk/debug/*.apk
